select credential_name,
       username,
       enabled
from   user_credentials
order by credential_name;

create table emp (
  empno    number(4,0), 
  ename    varchar2(10 byte), 
  job      varchar2(9 byte), 
  mgr      number(4,0), 
  hiredate date, 
  sal      number(7,2), 
  comm     number(7,2), 
  deptno   number(2,0), 
  constraint pk_emp primary key (empno)
);
  
insert into emp (empno,ename,job,mgr,hiredate,sal,comm,deptno) values (7369,'SMITH','CLERK',7902,to_date('17-DEC-80','DD-MON-RR'),800,null,20);
insert into emp (empno,ename,job,mgr,hiredate,sal,comm,deptno) values (7499,'ALLEN','SALESMAN',7698,to_date('20-FEB-81','DD-MON-RR'),1600,300,30);
insert into emp (empno,ename,job,mgr,hiredate,sal,comm,deptno) values (7521,'WARD','SALESMAN',7698,to_date('22-FEB-81','DD-MON-RR'),1250,500,30);
insert into emp (empno,ename,job,mgr,hiredate,sal,comm,deptno) values (7566,'JONES','MANAGER',7839,to_date('02-APR-81','DD-MON-RR'),2975,null,20);
insert into emp (empno,ename,job,mgr,hiredate,sal,comm,deptno) values (7654,'MARTIN','SALESMAN',7698,to_date('28-SEP-81','DD-MON-RR'),1250,1400,30);
insert into emp (empno,ename,job,mgr,hiredate,sal,comm,deptno) values (7698,'BLAKE','MANAGER',7839,to_date('01-MAY-81','DD-MON-RR'),2850,null,30);
insert into emp (empno,ename,job,mgr,hiredate,sal,comm,deptno) values (7782,'CLARK','MANAGER',7839,to_date('09-JUN-81','DD-MON-RR'),2450,null,10);
insert into emp (empno,ename,job,mgr,hiredate,sal,comm,deptno) values (7788,'SCOTT','ANALYST',7566,to_date('19-APR-87','DD-MON-RR'),3000,null,20);
insert into emp (empno,ename,job,mgr,hiredate,sal,comm,deptno) values (7839,'KING','PRESIDENT',null,to_date('17-NOV-81','DD-MON-RR'),5000,null,10);
insert into emp (empno,ename,job,mgr,hiredate,sal,comm,deptno) values (7844,'TURNER','SALESMAN',7698,to_date('08-SEP-81','DD-MON-RR'),1500,0,30);
insert into emp (empno,ename,job,mgr,hiredate,sal,comm,deptno) values (7876,'ADAMS','CLERK',7788,to_date('23-MAY-87','DD-MON-RR'),1100,null,20);
insert into emp (empno,ename,job,mgr,hiredate,sal,comm,deptno) values (7900,'JAMES','CLERK',7698,to_date('03-DEC-81','DD-MON-RR'),950,null,30);
insert into emp (empno,ename,job,mgr,hiredate,sal,comm,deptno) values (7902,'FORD','ANALYST',7566,to_date('03-DEC-81','DD-MON-RR'),3000,null,20);
insert into emp (empno,ename,job,mgr,hiredate,sal,comm,deptno) values (7934,'MILLER','CLERK',7782,to_date('23-JAN-82','DD-MON-RR'),1300,null,10);
commit;

/*
begin
  dbms_cloud.export_data (
    credential_name => 'obj_cred',
    file_uri_list   => 'https://swiftobjectstorage.uk-london-1.oraclecloud.com/v1/<namespace>/<bucket>/emp.csv',
    query           => 'select * from emp',
    format          => '{"type" : "CSV"}'
  );
end;
/
*/

drop table scheduled_extracts_cred;
drop table scheduled_extracts_dest;
drop table scheduled_extracts;

create table scheduled_extracts_cred (
    extract_cred_guid        NUMBER(*,0) GENERATED by default on null as IDENTITY,
        extract_cred_name        varchar2(20 char) not null
);
insert into scheduled_extracts_cred ( extract_cred_name ) values ( 'obj_cred');

create table scheduled_extracts_dest (
    extract_dest_guid        NUMBER(*,0) GENERATED by default on null as IDENTITY,
        extract_dest_name        varchar2(20 char) not null,
        extract_dest_loc        varchar2(1000 char) not null
);
insert into scheduled_extracts_dest ( extract_dest_name,extract_dest_loc ) values ( 'def_dest','https://swiftobjectstorage.uk-london-1.oraclecloud.com/v1/<namespace>/<bucket>/emp.csv');

create table scheduled_extracts(
        extract_guid        NUMBER(*,0) GENERATED by default on null as IDENTITY,
        extract_name        varchar2(200 char) not null,
        extract_owner       varchar2(200 char) ,
        extract_sql         varchar2(4000 char) default '' not null,
        extract_format         varchar2(4000 char) default '{"type" : "CSV"}' not null,
        extract_cred_guid   NUMBER(*,0) not null,
        extract_dest_guid   NUMBER(*,0) not null,
        extract_frq         varchar2(6 char) default 'DAY',
        extract_last_run    TIMESTAMP WITH TIME ZONE,
        extract_next_run    TIMESTAMP WITH TIME ZONE 
);

insert into scheduled_extracts(extract_name,extract_owner,extract_sql,extract_cred_guid,extract_dest_guid,extract_frq,extract_last_run) values
    ('EMP','stuart.leeke@<company>.com','select * from emp',1,1,'HOUR',sysdate );

    commit;

create or replace procedure run_extract
is
r_scheduled_extracts scheduled_extracts%ROWTYPE;
begin

SELECT *
  INTO r_scheduled_extracts
  FROM scheduled_extracts ;


  -- print out scheduler information
  dbms_output.put_line( r_scheduled_extracts.extract_guid || ' ' ||
  r_scheduled_extracts.extract_name || ' : ' || r_scheduled_extracts.extract_sql ||' ;' );

EXCEPTION
   WHEN OTHERS THEN
      dbms_output.put_line( SQLERRM );

    end;

exec run_extract;

